parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

    public.services: false

    startingPointHost: '%env(STARTING_POINT_DSN)%'
    backendHost: '%env(BACKEND_DSN)%'
    udp_logger_url: '%env(UDP_LOGGER_DSN)%'

    node_services_dirs:
        - '%kernel.project_dir%/config'

    applications:
        - '%kernel.project_dir%/config'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'
