parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

    public.services: false

    backendHost: '%env(BACKEND_DSN)%'

    node_services_dirs:
        - '%kernel.project_dir%/config'

    applications:
        - '%kernel.project_dir%/config'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'


    hbpf.data_store.file_system:
        class: Hanaboso\PipesPhpSdk\Storage\File\FileSystem

    hbpf.data_storage_manager:
        class: Hanaboso\PipesPhpSdk\Storage\DataStorage\DataStorageManager
        arguments:
            - '@hbpf.data_store.file_system'
