version: '2.4'

services:
    wait-for-it:
        image: hanabosocom/wait-for-it:master

    php-sdk:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./php-sdk:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            PHP_WEBROOT: /var/www/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            KERNEL_CLASS: Pipes\PhpSdk\Kernel
            BACKEND_DSN: ${BACKEND_URL}
            STARTING_POINT_DSN: ${DEV_IP}:82
            METRICS_SERVICE: mongo
            METRICS_DSN: mongodb://mongo
            METRICS_DB: metrics
            MONGODB_DSN: mongodb://mongo
            MONGODB_DB: tutorial
            RABBITMQ_DSN: amqp://rabbitmq:5672
            UDP_LOGGER_DSN: logstash:5005
        mem_limit: 512MB

    nodejs-sdk:
        image: nodejs-sdk:tag
        build: nodejs-sdk/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./nodejs-sdk/:/var/www
        environment:
            # Envs for tests are load from nodejs-sdk/.jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: debug
            CRYPT_SECRET: ThisIsNotSoSecret
            BACKEND_URL: http://127.0.0.10:8080
            UDP_LOGGER_DSN: logstash:5005
            METRICS_DSN: mongodb://mongo:27017/metrics
            MONGODB_DSN: mongodb://mongo:27017/tutorial
        command: sh -c 'pnpm install && pnpm run start'
        mem_limit: 512MB

    status-service:
        image: orchesty/status-service:${VERSION}
        restart: on-failure
        environment:
            RABBITMQ_DSN: amqp://rabbitmq:5672
        mem_limit: 32MB

    notification-sender-api:
        image: orchesty/notification-sender:${VERSION}
        environment:
            MONGO_HOST: mongo
        mem_limit: 32MB

    notification-sender-consumer:
        image: orchesty/notification-sender:${VERSION}
        environment:
            RABBITMQ_DSN: amqp://rabbitmq:5672
            MONGO_HOST: mongo
        command: bin/console rabbit_mq:consumer:notification
        mem_limit: 32MB

    multi-counter:
        image: orchesty/counter:${VERSION}
        environment:
            RABBITMQ_DSN: amqp://rabbitmq:5672
            MONGODB_DSN: mongodb://mongo/tutorial
            METRICS_DSN: mongodb://mongo/metrics
        command: /bin/counter start
        mem_limit: 64MB

    repeater:
        image: orchesty/pf-bridge:${VERSION}
        environment:
            MONGO_HOST: mongo
            REPEATER_CHECK_TIMEOUT: 5000
        command: ./dist/src/bin/pipes.js start repeater
        mem_limit: 64MB

    starting-point:
        image: orchesty/starting-point:${VERSION}
        environment:
            MONGO_DSN: mongodb://mongo/tutorial?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            METRICS_DSN: mongodb://mongo/metrics?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            RABBIT_COUNTER_QUEUE_DURABLE: 'true'
            RABBIT_QUEUE_DURABLE: 'true'
            RABBIT_DELIVERY_MODE: 2
        ports:
            - ${DEV_IP}:82:8080
        mem_limit: 64MB

    topology-api:
        image: orchesty/topology-api:${VERSION}
        environment:
            DEPLOYMENT_PREFIX: skeleton
            GENERATOR_NETWORK: skeleton_default
            GENERATOR_MODE: compose
            GENERATOR_PATH: /srv/topology
            MONGO_DSN: mongodb://mongo/tutorial?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            RABBITMQ_HOST: rabbitmq
            PROJECT_SOURCE_PATH: ${PROJECT_SOURCE_PATH}/topology
            WORKER_DEFAULT_LIMIT_CPU: 1
            WORKER_DEFAULT_LIMIT_MEMORY: 200m
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ./topology:/srv/topology
        mem_limit: 64MB

    detector:
        image: orchesty/detector:${VERSION}
        environment:
            METRICS_DSN: mongodb://mongo/metrics?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
        mem_limit: 32MB

    cron-api:
        image: orchesty/cron:${VERSION}
        environment:
            MONGO_DSN: mongodb://mongo/cron?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            MONGO_COLLECTION: cron
        mem_limit: 32MB

    limiter:
        image: orchesty/limiter:${VERSION}
        environment:
            LIMITER_ADDR: 0.0.0.0:3333
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USER: guest
            RABBITMQ_PASS: guest
            MONGO_HOST: mongodb://mongo/tutorial
            MONGO_DB: tutorial
            MONGO_COLLECTION: LimiterMessages
            LOGSTASH_HOST: logstash
            LOGSTASH_PORT: "5120"
        mem_limit: 32MB

    frontend:
        image: orchesty/frontend:${VERSION}
        environment:
            BACKEND_URL: ${BACKEND_URL}
            FRONTEND_URL: '/'
            STARTINGPOINT_URL: http://${DEV_IP}:82
        ports:
            - ${DEV_IP}:80:80
        mem_limit: 32MB

    backend:
        image: orchesty/backend:${VERSION}
        ports:
            - ${DEV_IP}:8080:80
        environment:
            BACKEND_DSN: ${BACKEND_URL}/
            FRONTEND_DSN: ${FRONTEND_URL}/
            NOTIFICATION_DSN: notification-sender-api
            RABBITMQ_DSN: amqp://rabbitmq:5672/
            MONGODB_DSN: mongodb://mongo
            MONGODB_DB: tutorial
            METRICS_DSN: mongodb://mongo
            METRICS_DB: metrics
            METRICS_SERVICE: mongo
            CRON_DSN: cron-api:8080
            MONOLITH_API_DSN: php-sdk
            STARTING_POINT_DSN: starting-point:8080
            TOPOLOGY_API_DSN: topology-api:8080
            WORKER_DEFAULT_PORT: 8008
            DOCKER_REGISTRY: orchesty
            DOCKER_PF_BRIDGE_IMAGE: bridge:${VERSION}
            JWT_KEY: tutorial_key
            CRYPT_SECRET: ThisIsNotSoSecret
            X_AUTH_KEY: x_auth_key
        mem_limit: 64MB

    logstash:
        image: orchesty/logstash:${VERSION}
        environment:
            - MONGO_DSN=mongodb://mongo:27017
            - MONGO_DB=tutorial
            - MONGO_COLLECTION=Logs
            - LS_JAVA_OPTS=-Xms512m -Xmx512m
        mem_limit: 768MB

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db
        mem_limit: 256MB

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${DEV_IP}:15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        mem_limit: 512MB

volumes:
    mongodb:
    rabbitmq:

networks:
    default:
        name: tutorial_default
