version: '2.4'

services:
    php-sdk:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./php-sdk:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 1
            APP_ENV: dev
            PHP_IDE_CONFIG: ${PHP_IDE}
            PHP_WEBROOT: /var/www/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            KERNEL_CLASS: Pipes\PhpSdk\Kernel
            BACKEND_HOST: ${DEV_IP}:8080
            METRICS_DSN: mongodb://mongo/metrics
            METRICS_DB: metrics
            MONGODB_DSN: mongodb://mongo/tutorial
            MONGODB_DB: tutorial
            RABBITMQ_DSN: amqp://rabbitmq:5672
            METRICS_SERVICE: mongo
            USER_TASK_LISTENER_ENABLE: 0
        mem_limit: 64MB

    batch-connector:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        restart: on-failure
        volumes:
            - ./php-sdk:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 1
            APP_ENV: dev
            BACKEND_HOST: ${DEV_IP}:8080
            RABBITMQ_DSN: amqp://rabbitmq:5672
            METRICS_DSN: mongodb://mongo/metrics
            METRICS_DB: metrics
            MONGODB_DSN: mongodb://mongo/tutorial
            MONGODB_DB: tutorial
            METRICS_SERVICE: mongo
            USER_TASK_LISTENER_ENABLE: 0
        command: bin/console rabbit_mq:consumer:batch-connector
        mem_limit: 64MB

    long-running-node:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        restart: on-failure
        volumes:
            - ./php-sdk:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 1
            APP_ENV: dev
            RABBITMQ_DSN: amqp://rabbitmq:5672
            METRICS_DSN: mongodb://mongo/metrics
            METRICS_DB: metrics
            MONGODB_DSN: mongodb://mongo/tutorial
            MONGODB_DB: tutorial
            METRICS_SERVICE: mongo
            USER_TASK_LISTENER_ENABLE: 0
        command: bin/console rabbit_mq:consumer:long-running-node
        mem_limit: 64MB

    status-service:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        restart: on-failure
        volumes:
            - ./php-sdk:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            APP_DEBUG: 1
            APP_ENV: dev
            RABBITMQ_DSN: amqp://rabbitmq:5672
            METRICS_DSN: mongodb://mongo/metrics
            METRICS_DB: metrics
            MONGODB_DSN: mongodb://mongo/tutorial
            MONGODB_DB: tutorial
            METRICS_SERVICE: mongo
            USER_TASK_LISTENER_ENABLE: 0
        command: bin/console rabbit_mq:consumer:status-service
        mem_limit: 64MB

    notification-sender-api:
        image: hanaboso/pipes-notification-sender:master
        environment:
            MONGO_HOST: mongo
        mem_limit: 64MB

    notification-sender-consumer:
        image: hanaboso/pipes-notification-sender:master
        environment:
            RABBITMQ_DSN: amqp://rabbitmq:5672
            MONGO_HOST: mongo
        command: bin/console rabbit_mq:consumer:notification
        mem_limit: 64MB

    multi-probe:
        image: hanaboso/pipes-multi-probe:master
        mem_limit: 64MB

    multi-counter:
        image: hanaboso/pipes-pf-bridge:master
        environment:
            METRICS_SERVICE: mongo
            METRICS_HOST: mongo
            METRICS_PORT: 27017
            PROGRESS_DSN: mongodb://mongo/tutorial
            PROGRESS_SAVE: 'true'
        command: ./dist/src/bin/pipes.js start multi_counter
        mem_limit: 128MB

    repeater:
        image: hanaboso/pipes-pf-bridge:master
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: guest
            RABBITMQ_PASS: guest
            RABBITMQ_VHOST: /
            MONGO_HOST: mongo
            REPEATER_CHECK_TIMEOUT: 5000
        command: ./dist/src/bin/pipes.js start repeater
        mem_limit: 128MB

    starting-point:
        image: hanaboso/pipes-starting-point:master
        environment:
            MONGO_DSN: mongodb://mongo/tutorial?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            METRICS_DSN: mongodb://mongo/metrics?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            RABBIT_COUNTER_QUEUE_DURABLE: 'true'
            RABBIT_QUEUE_DURABLE: 'true'
            RABBIT_DELIVERY_MODE: 2
        ports:
            - ${DEV_IP}:82:8080
        mem_limit: 64MB

    topology-api:
        image: hanaboso/pipes-topology-api-v2:master
        environment:
            DEPLOYMENT_PREFIX: tutorial
            GENERATOR_NETWORK: tutorial_default
            GENERATOR_MODE: compose
            GENERATOR_PATH: /srv/topology
            MONGO_DSN: mongodb://mongo/tutorial?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            RABBITMQ_HOST: rabbitmq
            PROJECT_SOURCE_PATH: ${PROJECT_SOURCE_PATH}/topology
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ./topology:/srv/topology
        mem_limit: 64MB

    telegraf:
        image: hanaboso/pipes-telegraf:master
        environment:
            METRICS_DSN: mongodb://mongo/metrics?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
        mem_limit: 64MB

    cron-api:
        image: hanaboso/pipes-cron:master
        environment:
            MONGO_DSN: mongodb://mongo/cron?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500
            MONGO_COLLECTION: cron
        mem_limit: 64MB

    frontend:
        image: hanaboso/pipes-frontend:master
        environment:
            BACKEND_URL: ${BACKEND_URL}
            FRONTEND_URL: ${FRONTEND_URL}
            STARTING_POINT_URL: http://${DEV_IP}:82
        ports:
            - ${DEV_IP}:80:80
        mem_limit: 64MB

    backend:
        image: hanaboso/pipes-pf-bundle:master
        ports:
            - ${DEV_IP}:8080:80
        environment:
            BACKEND_DSN: ${BACKEND_URL}/
            FRONTEND_DSN: ${FRONTEND_URL}/
            NOTIFICATION_DSN: notification-sender-api
            RABBIT_DSN: amqp://rabbitmq:5672/
            MONGODB_DSN: mongodb://mongo/tutorial
            MONGODB_DB: tutorial
            METRICS_SERVICE: mongo
            METRICS_HOST: mongo
            METRICS_PORT: 27017
            CRON_DSN: cron-api:8080
            MONOLITH_API_DSN: php-sdk
            MULTI_PROBE_DSN: multi-probe:8007
            STARTING_POINT_DSN: starting-point:8080
            TOPOLOGY_API_DSN: topology-api:8080
            WORKER_DEFAULT_PORT: 8008
            DOCKER_REGISTRY: hanaboso
            DOCKER_PF_BRIDGE_IMAGE: pipes-pf-bridge:master
        mem_limit: 64MB

    logstash:
        image: hanaboso/pipes-logstash-mongo:master
        environment:
            - MONGO_DSN=mongodb://mongo:27017
            - MONGO_DB=tutorial
            - MONGO_COLLECTION=Logs
            - LS_JAVA_OPTS=-Xms512m -Xmx512m
        mem_limit: 768MB

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db
        mem_limit: 256MB

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${DEV_IP}:15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        mem_limit: 512MB

volumes:
    mongodb:
    rabbitmq:

networks:
    default:
        name: tutorial_default
