version: '2.4'

services:
    wait-for-it:
        image: hanabosocom/wait-for-it:master

    php-sdk:
        image: hanabosocom/php-dev:php-8.2-alpine
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./php-sdk:/var/www:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            PHP_WEBROOT: /var/www/public
            COMPOSER_HOME: ${HOME}/dev/.composer
            KERNEL_CLASS: Pipes\PhpSdk\Kernel
            CRYPT_SECRET: ${CRYPT_SECRET}
            BACKEND_DSN: ${BACKEND_URL}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            WORKER_API_HOST: ${WORKER_API_HOST}
            ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
        mem_limit: 512MB
        depends_on:
            - fluentd
            - mongo

    nodejs-sdk:
        image: nodejs-sdk:tag
        build: nodejs-sdk/docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./nodejs-sdk/:/var/www
        environment:
            # Envs for tests are load from nodejs-sdk/.jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: debug
            CRYPT_SECRET: ${CRYPT_SECRET}
            BACKEND_URL: ${BACKEND_URL}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            WORKER_API_HOST: ${WORKER_API_HOST}
            ORCHESTY_API_KEY: ${ORCHESTY_API_KEY}
        command: sh -c 'pnpm install && pnpm run start'
        mem_limit: 512MB
        depends_on:
            - fluentd
            - mongo

    multi-counter:
        image: orchesty/counter:${VERSION}
        environment:
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
            UDP_LOGGER_URL: ${UDP_LOGGER_DSN}
        mem_limit: 64MB
        depends_on:
            - mongo
            - rabbitmq

    starting-point:
        image: orchesty/starting-point:${VERSION}
        environment:
            MONGO_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            RABBIT_DELIVERY_MODE: 2
        ports:
            - ${DEV_IP}:82:8080
        mem_limit: 64MB
        depends_on:
            - fluentd
            - mongo
            - rabbitmq

    topology-api:
        image: orchesty/topology-api:${VERSION}
        environment:
            DEPLOYMENT_PREFIX: ${MAIN_DB}
            GENERATOR_NETWORK: ${NETWORK_NAME}
            PLATFORM: ${PLATFORM}
            GENERATOR_PATH: /srv/topology
            PROJECT_SOURCE_PATH: ${PROJECT_SOURCE_PATH}/topology
            MONGO_DSN: ${MONGO_DSN}
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
            - ./topology:/srv/topology
        mem_limit: 64MB
        depends_on:
            - mongo

    detector:
        image: orchesty/detector:${VERSION}
        environment:
            MONGO_DSN: ${MONGO_DSN}
            METRICS_DSN: ${METRICS_DSN}
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            PLATFORM: ${PLATFORM}
            DOCKER_NETWORK: ${NETWORK_NAME}
        mem_limit: 32MB
        depends_on:
            - mongo
            - rabbitmq

    cron-api:
        image: orchesty/cron:${VERSION}
        environment:
            MONGO_DSN: ${MONGO_DSN}
            MONGO_COLLECTION: cron
            STARTING_POINT_DSN: ${STARTING_POINT_DSN}
        mem_limit: 32MB
        depends_on:
            - mongo

    limiter:
        image: orchesty/limiter:${VERSION}
        environment:
            LIMITER_ADDR: 0.0.0.0:3333
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGO_DSN: ${MONGO_DSN}
            UDP_LOGGER_DSN: ${UDP_LOGGER_DSN}
        mem_limit: 32MB
        depends_on:
            - fluentd
            - mongo
            - rabbitmq

    worker-api:
        image: orchesty/worker-api:${VERSION}
        environment:
            MONGODB_DSN: ${MONGO_DSN}
            FLUENTD_DSN: ${UDP_LOGGER_DSN}
        mem_limit: 64MB
        depends_on:
            - fluentd
            - mongo

    frontend:
        image: orchesty/frontend:${VERSION}
        environment:
            BACKEND_URL: ${BACKEND_URL}
            FRONTEND_URL: '/'
            STARTINGPOINT_URL: http://${DEV_IP}:82
        ports:
            - ${DEV_IP}:80:80
        mem_limit: 32MB

    backend:
        image: orchesty/backend:${VERSION}
        ports:
            - ${DEV_IP}:8080:80
        environment:
            BACKEND_URL: ${BACKEND_URL}/
            FRONTEND_URL: ${FRONTEND_URL}/
            RABBITMQ_DSN: ${RABBITMQ_DSN}
            MONGODB_DSN: ${MONGO_DSN}
            MONGODB_DB: ${MAIN_DB}
            METRICS_DSN: ${METRICS_DSN}
            METRICS_DB: metrics
            CRON_DSN: cron-api:8080
            STARTING_POINT_URL: ${STARTING_POINT_DSN}
            TOPOLOGY_API_DSN: topology-api:8080
            DOCKER_PF_BRIDGE_IMAGE: orchesty/bridge:${VERSION}
            JWT_KEY: ${JWT_KEY}
            INSTALLER_DIRS: '["/var/www/topology"]'
        mem_limit: 64MB
        depends_on:
            - fluentd
            - mongo
            - rabbitmq

    fluentd:
        image: orchesty/fluentd:${VERSION}
        environment:
            - MONGO_DSN=${MONGO_DSN}
            - MONGO_COLLECTION=Logs
        mem_limit: 128MB

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db
        mem_limit: 256MB

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${DEV_IP}:15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        mem_limit: 512MB

volumes:
    mongodb:
    rabbitmq:

networks:
    default:
        name: ${NETWORK_NAME}
