# ./config/connector/connector.yaml
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'


    # BASIC Connectors
    hbpf.connector.get-users:
        class: Pipes\PhpSdk\Connector\Users\GetUsersConnector
        arguments:
            - '@hbpf.transport.curl_manager'

    # SendGrid Connectors
    hbpf.connector.send-grid.send-email:
        class: Pipes\PhpSdk\Connector\SendGrid\SendGridSendEmailConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        calls:
            - ['setApplication', ['@hbpf.application.send-grid']]

    # HubSpot Connectors
    hbpf.connector.hub-spot.create-multiple-contact:
        class: Pipes\PhpSdk\Connector\HubSpot\HubSpotCreateMultipleContactsConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        calls:
            - ['setApplication', ['@hbpf.application.hub-spot']]

    hbpf.connector.hub-spot.create-contact:
        class: Pipes\PhpSdk\Connector\HubSpot\HubSpotCreateContactConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        calls:
            - ['setApplication', ['@hbpf.application.hub-spot']]

    # Google Connectors
    hbpf.connector.google-drive.upload-file:
        class: Pipes\PhpSdk\Connector\Google\GoogleDriveUploadFileConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'
        calls:
            - ['setApplication', ['@hbpf.application.google-drive']]