# ./config/connector/connector.yaml
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'

    hbpf.connector.jsonplaceholder-get-users:
        class: Pipes\PhpSdk\Connector\GetUsersConnector
        calls:
            - ['setSender', ['@hbpf.transport.curl_manager']]

    hbpf.connector.git-hub-get-repository:
        class: Pipes\PhpSdk\Connector\GitHubRepositoryConnector
        calls:
            - ['setApplication', ['@hbpf.application.git-hub']]
            - ['setSender', ['@hbpf.transport.curl_manager']]
            - ['setDb', ['@doctrine_mongodb.odm.default_document_manager']]

    hbpf.connector.hub-spot-create-contact:
        class: Pipes\PhpSdk\Connector\HubSpotCreateContactConnector
        calls:
            - ['setApplication', ['@hbpf.application.hub-spot']]
            - ['setSender', ['@hbpf.transport.curl_manager']]
            - ['setDb', ['@doctrine_mongodb.odm.default_document_manager']]
