# ./config/connector/connector.yaml
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'


    hbpf.connector.get-users:
        class: Pipes\PhpSdk\Connector\Users\GetUsersConnector
        arguments:
            - '@hbpf.transport.curl_manager'

    hbpf.connector.send-grid.send-email:
        class: Pipes\PhpSdk\Connector\SendGrid\SendGridSendEmailConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'

    hbpf.connector.hub-spot.create-contact:
        class: Pipes\PhpSdk\Connector\HubSpot\HubSpotCreateContactConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.transport.curl_manager'