parameters:
    ##########################
    #   Database Locator     #
    ##########################
    database_type: 'ODM' # 'ORM'

    ##########################
    #        Metrics         #
    ##########################
    metrics_service: '%env(string:METRICS_SERVICE)%'
    #MongoDb sender
    mongodb.monolith_table: monolith
    mongodb.connector_table: connectors
    mongodb.node_table: pipes_node
    mongodb.rabbit_table: rabbitmq
    mongodb.counter_table: pipes_counter

services:
    _defaults:
        public: '%public.services%'

    ##########################
    #        Crypts          #
    ##########################

    hbpf.commons.crypt.crypt_manager:
        class: Hanaboso\CommonsBundle\Crypt\CryptManager
        arguments:
            - ['@hbpf.commons.crypt.windwalker']

    hbpf.commons.crypt.windwalker:
        class: Hanaboso\CommonsBundle\Crypt\Impl\WindwalkerCrypt
        arguments:
            - '%kernel.secret%'

    ##########################
    #        Metrics         #
    ##########################

    hbpf.system_metrics_listener:
        class: Hanaboso\CommonsBundle\Listener\SystemMetricsListener
        arguments:
            - '@hbpf.metrics_monolith.loader'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber, event: kernel.terminate }
            - { name: kernel.event_subscriber, event: kernel.controller }

    hbpf.metrics.mongodb_connector:
        class: Hanaboso\CommonsBundle\Metrics\Impl\MongoDbSender
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'
            - '%mongodb.connector_table%'

    hbpf.metrics.mongodb_monolith:
        class: Hanaboso\CommonsBundle\Metrics\Impl\MongoDbSender
        arguments:
            - '@doctrine_mongodb.odm.metrics_document_manager'
            - '%mongodb.monolith_table%'

    hbpf.metrics_connector.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '@hbpf.metrics.mongodb_connector'

    hbpf.metrics_monolith.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '@hbpf.metrics.mongodb_monolith'

    ##########################
    #      File Storage      #
    ##########################

#    hbpf.file_storage.driver.mongo:
#        class: Hanaboso\CommonsBundle\FileStorage\Driver\Impl\Mongo\MongoFileDriver
#        arguments:
#            - '@doctrine_mongodb.odm.default_document_manager'
#            - '@hbpf.path_generator.hash'
#
#    hbpf.path_generator.hash:
#        class: Hanaboso\CommonsBundle\FileStorage\PathGenerator\HashPathGenerator
#        arguments:
#
#    hbpf.file_storage.locator:
#        class: Hanaboso\CommonsBundle\FileStorage\Driver\FileStorageDriverLocator
#        arguments:
#            - '@hbpf.file_storage.driver.mongo'
#            - '@hbpf.file_storage.driver.mongo'
#            - '@hbpf.file_storage.driver.mongo'
#
#    hbpf.file_storage:
#        class: Hanaboso\CommonsBundle\FileStorage\FileStorage
#        arguments:
#            - '@hbpf.file_storage.locator'
#            - '@hbpf.database_manager_locator'
#            - 'Hanaboso\CommonsBundle\FileStorage\Document\File'

    ##########################
    #    Database Locator    #
    ##########################

    hbpf.database_manager_locator:
        class: Hanaboso\CommonsBundle\Database\Locator\DatabaseManagerLocator
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - null
            - '%database_type%'


    ##########################
    #   Transport Services   #
    ##########################

    hbpf.transport.curl_client_factory:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlClientFactory

    hbpf.transport.udp_sender:
        class: Hanaboso\CommonsBundle\Transport\Udp\UDPSender

    hbpf.transport.curl_manager:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlManager
        arguments:
            - '@hbpf.transport.curl_client_factory'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
            - ['setMetricsSender', ['@hbpf.metrics_connector.loader']] ## Optional metrics sender
