parameters:
    ##########################
    #        Metrics         #
    ##########################
    #MongoDb sender
    mongodb.monolith_table: monolith
    mongodb.connector_table: connectors
    mongodb.node_table: pipes_node
    mongodb.rabbit_table: rabbitmq
    mongodb.counter_table: pipes_counter

    ##########################
    #        Worker Api      #
    ##########################
    worker-api: '%env(string:WORKER_API_HOST)%'
    api-key: '%env(string:ORCHESTY_API_KEY)%'

services:
    _defaults:
        public: '%public.services%'

    ##########################
    #        Crypts          #
    ##########################
    hbpf.commons.crypt.crypt_manager:
        class: Hanaboso\CommonsBundle\Crypt\CryptManager
        arguments:
            - ['@hbpf.commons.crypt.windwalker']

    hbpf.commons.crypt.windwalker:
        class: Hanaboso\CommonsBundle\Crypt\Impl\WindwalkerCrypt
        arguments:
            - '%kernel.secret%'

    ##########################
    #        Worker Api      #
    ##########################
    hbpf.worker-api:
        class: Hanaboso\CommonsBundle\WorkerApi\Client
        arguments:
            - '@hbpf.transport.curl_client_factory'
            - '%worker-api%'
            - '%api-key%'

    ##########################
    #        Metrics         #
    ##########################
    hbpf.system_metrics_listener:
        class: Hanaboso\CommonsBundle\Listener\SystemMetricsListener
        arguments:
            - '@hbpf.metrics_monolith.loader'
        calls:
            - [ 'setLogger', [ '@monolog.logger.commons' ] ]
        tags:
            - { name: kernel.event_subscriber, event: kernel.terminate }
            - { name: kernel.event_subscriber, event: kernel.controller }

    hbpf.metrics.curl_connector:
        class: Hanaboso\CommonsBundle\Metrics\Impl\CurlSender
        arguments:
            - '@hbpf.worker-api'

    hbpf.metrics.curl_monolith:
        class: Hanaboso\CommonsBundle\Metrics\Impl\CurlSender
        arguments:
            - '@hbpf.worker-api'

    hbpf.metrics_connector.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '@hbpf.metrics.curl_connector'

    hbpf.metrics_monolith.loader:
        class: Hanaboso\CommonsBundle\Metrics\MetricsSenderLoader
        arguments:
            - '@hbpf.metrics.curl_monolith'


    ##########################
    #   Transport Services   #
    ##########################
    hbpf.transport.curl_client_factory:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlClientFactory

    hbpf.transport.curl_manager:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlManager
        arguments:
            - '@hbpf.transport.curl_client_factory'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
            - ['setMetricsSender', ['@hbpf.metrics_connector.loader']] ## Optional metrics sender
