parameters:
    stdout_path: 'php://stdout'

monolog:
    use_microseconds: false
    channels: [authorization, commons, connector, ftp, parser_table, rabbit_mq, stdout]
    handlers:
        main:
            type: service
            id: http_handler
            level: warning
        # Handler for docker container
        stdout:
            type:  stream
            path:  "%stdout_path%"
            level: info
            formatter: logstash_formatter
            max_files: 10
            channels: '!php'

services:
    _defaults:
        public: '%public.services%'

    logstash_formatter:
        class: Hanaboso\CommonsBundle\Monolog\LogstashFormatter

    http_handler:
        class: Hanaboso\CommonsBundle\Monolog\HttpHandler
        calls:
            - ['setFormatter', ['@logstash_formatter']]
        arguments:
            - '@hbpf.worker-api'
