# Repeater
rabbit_mq:
    connections:
        default:
            dsn: '%env(string:RABBITMQ_DSN)%'

    exchanges:
        repeater:
            durable: true
            type: direct

    queues:
        pipes.batch_connector:
        pipes.batch:
