hb_pf_application:
    resource: "@HbPFApplicationBundle/Controller"
    type: annotation

hb_pf_app_store:
    resource: "@HbPFAppStoreBundle"
    type: annotation

hb_pf_connector:
    resource: "@HbPFConnectorBundle/Controller"
    type: annotation

hb_pf_custom_node:
    resource: "@HbPFCustomNodeBundle/Controller"
    type: annotation
