hb_pf_application:
    resource: "@HbPFApplicationBundle"
    type: attribute

hb_pf_connector:
    resource: "@HbPFConnectorBundle"
    type: attribute

hb_pf_batch:
    resource: "@HbPFBatchBundle"
    type: attribute

hb_pf_custom_node:
    resource: "@HbPFCustomNodeBundle"
    type: attribute
