# ./config/custom_node/custom_node.yaml
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'

    hbpf.custom_node.hub-spot.create-multiple-contact-mapper:
        class: Pipes\PhpSdk\Mapper\HubSpot\HubSpotCreateMultipleContactsMapper

    hbpf.custom_node.hub-spot.create-contact-mapper:
        class: Pipes\PhpSdk\Mapper\HubSpot\HubSpotCreateContactMapper