# ./config/custom_node/custom_node.yaml
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'

    hbpf.custom_node.hello-world:
        class: Pipes\PhpSdk\Mapper\HelloWorld
